
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'left+-left*/rightUMINUSNUMBER VAR\n\tstat : VAR "=" exp\n\t\n\tstat : exp\n\t\n\texp : exp "+" exp\n\t\n\texp : exp "-" exp\n\t\n\texp : exp "*" exp\n\t\n\texp : exp "/" exp\n\t\n\texp : "-" exp %prec UMINUS\n\t\n\texp : NUMBER\n\t\n\texp : VAR\n\t'
    
_lr_action_items = {'VAR':([0,4,6,7,8,9,10,],[2,12,12,12,12,12,12,]),'-':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[4,-9,8,4,-8,4,4,4,4,4,-7,-9,8,-3,-4,-5,-6,]),'NUMBER':([0,4,6,7,8,9,10,],[5,5,5,5,5,5,5,]),'$end':([1,2,3,5,11,12,13,14,15,16,17,],[0,-9,-2,-8,-7,-9,-1,-3,-4,-5,-6,]),'=':([2,],[6,]),'+':([2,3,5,11,12,13,14,15,16,17,],[-9,7,-8,-7,-9,7,-3,-4,-5,-6,]),'*':([2,3,5,11,12,13,14,15,16,17,],[-9,9,-8,-7,-9,9,9,9,-5,-6,]),'/':([2,3,5,11,12,13,14,15,16,17,],[-9,10,-8,-7,-9,10,10,10,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stat':([0,],[1,]),'exp':([0,4,6,7,8,9,10,],[3,11,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stat","S'",1,None,None,None),
  ('stat -> VAR = exp','stat',3,'p_production0','File(Converted to PLY).py',37),
  ('stat -> exp','stat',1,'p_production1','File(Converted to PLY).py',43),
  ('exp -> exp + exp','exp',3,'p_production2','File(Converted to PLY).py',49),
  ('exp -> exp - exp','exp',3,'p_production3','File(Converted to PLY).py',55),
  ('exp -> exp * exp','exp',3,'p_production4','File(Converted to PLY).py',61),
  ('exp -> exp / exp','exp',3,'p_production5','File(Converted to PLY).py',67),
  ('exp -> - exp','exp',2,'p_production6','File(Converted to PLY).py',73),
  ('exp -> NUMBER','exp',1,'p_production7','File(Converted to PLY).py',79),
  ('exp -> VAR','exp',1,'p_production8','File(Converted to PLY).py',85),
]
